### PR TITLE
fixed exceptions being thrown for a hr_max,avg,min and cadence child …

### PR DESCRIPTION
**Pull request by terra-alex**
…not found

### CODE REVIEW

**Comment by vkurup** [comment]
Apologies for the delay. I'd prefer not to include all of the `.idea` files in this repo, so if you can remove those, I'll merge this.

**Comment by terra-alex** [comment]
Sorry for that! Fixing now

**Comment by vkurup** [comment]
Looks like `pre-commit` doesn't like the formatting of some of your changes. I'll go ahead and merge this and fix it before releasing Thanks for your contribution!

**Comment by terra-alex** [comment]
Thanks for the help as well! I've taken some parts of the project for my own (and attributed them according to the license you provided) and added some extra functionality, I'll add it on another PR here soon!

**Pull request merged**
