### PR TITLE
Average altitude added

### PR DESCRIPTION
**Pull request by firefly-cpp**
Average altitude seems to be very useful.

Please check it out.

### CODE REVIEW

**Comment by vkurup** [comment]
Thank you! It would be nice to add 2 things to this PR:

1. Update the README to inform users that we now also extract these data points.
2. Two tests to `test_tcxparser.py` to exercise the new functionality.

Feel free to add to your branch and push again, or else I'll plan to make those updates in a few days.

**Comment by firefly-cpp** [comment]
Added.

**Comment by vkurup** [comment]
Thank you!

**Comment by vkurup** [comment]
Released to PyPI as [version 0.7.0](https://pypi.python.org/pypi/python-tcxparser/0.7.0)

**Comment by firefly-cpp** [comment]
Thank you very much.

**Pull request merged**
